#!/usr/bin/env node
/**
 * make-roster.mjs — turn a plain list of artist names into config/artists.json.
 *
 * No dependencies. Needs Node 18 or newer.
 *
 *   node tools/make-roster.mjs roster.txt
 *   node tools/make-roster.mjs roster.txt --merge
 *
 * roster.txt is one artist per line, exactly as you'd write it on a roster.
 * Blank lines and lines starting with # are ignored. So is anything after a
 * tab or a pipe, which lets you paste a two-column list straight out of a doc.
 *
 * Once config/artists.json has artists in it, that list is AUTHORITATIVE: only
 * those artists appear in the dashboard, and any Sprout profile matching none of
 * them is reported as unassigned rather than inventing a roster row. That is the
 * point — it stops the same artist showing up three times because their accounts
 * are named inconsistently.
 *
 * --merge keeps any chartmetricArtistId, realcountArtistName, fanProfileIds and
 * sproutProfileNames already in the file, so re-running never loses your work.
 */

import { existsSync, readFileSync, writeFileSync, copyFileSync } from 'node:fs'
import { resolve } from 'node:path'

const OUT = resolve(process.cwd(), 'config/artists.json')

const args = process.argv.slice(2)
const inputPath = args.find((a) => !a.startsWith('--'))
const merge = args.includes('--merge')

if (!inputPath) {
  console.error(`
Usage: node tools/make-roster.mjs <roster.txt> [--merge]

  roster.txt   one artist name per line
  --merge      keep IDs and aliases already in config/artists.json
`)
  process.exit(1)
}

if (!existsSync(inputPath)) {
  console.error(`\nNo such file: ${inputPath}\n`)
  process.exit(1)
}

const names = readFileSync(inputPath, 'utf8')
  .split('\n')
  // Allow pasted two-column lists: keep only the first cell.
  .map((line) => line.split(/\t|\|/)[0].trim())
  .filter((line) => line && !line.startsWith('#'))

if (names.length === 0) {
  console.error('\nThat file has no artist names in it.\n')
  process.exit(1)
}

const seen = new Set()
const unique = []
for (const name of names) {
  const key = name.toLowerCase()
  if (seen.has(key)) {
    console.log(`  skipped duplicate line: ${name}`)
    continue
  }
  seen.add(key)
  unique.push(name)
}

// Preserve everything a previous run or a human added.
const existing = new Map()
if (merge && existsSync(OUT)) {
  try {
    const prev = JSON.parse(readFileSync(OUT, 'utf8'))
    for (const a of prev.artists ?? []) existing.set(a.name.toLowerCase(), a)
  } catch (err) {
    console.error(`\nCould not read the existing ${OUT}: ${err.message}`)
    console.error('Fix or delete it, or re-run without --merge.\n')
    process.exit(1)
  }
}

const artists = unique.map((name) => {
  const prior = existing.get(name.toLowerCase())
  return prior ? { ...prior, name } : { name }
})

const carried = artists.filter((a) => Object.keys(a).length > 1).length

const payload = {
  _comment: [
    'Generated by tools/make-roster.mjs. Safe to edit by hand.',
    '',
    'This list is authoritative: only these artists appear in the dashboard, and',
    'Sprout profiles matching none of them are reported as unassigned rather than',
    'creating a roster row. Run `npm run verify:apis` to see what did not match.',
    '',
    'Per artist you can add:',
    '  sproutProfileNames  other account names that belong to this artist',
    '  sproutProfileIds    exact Sprout profile IDs, when a name will never match',
    '  chartmetricArtistId pin when the name lookup finds the wrong artist',
    '  realcountArtistName the name RealCount books them under, if different',
    '  fanProfileIds       profiles to force to fan-run',
    '  artistProfileIds    profiles to force to artist-owned',
    '',
    'Set "allowUnlistedArtists": true to also auto-create artists from unmatched',
    'profile names, which is the old guessing behaviour.',
  ],
  excludeProfileNames: [],
  artists,
}

if (existsSync(OUT) && !merge) {
  copyFileSync(OUT, `${OUT}.backup`)
  console.log(`\n  Backed up the previous file to ${OUT}.backup`)
}

writeFileSync(OUT, `${JSON.stringify(payload, null, 2)}\n`, 'utf8')

console.log(`\n  Wrote ${OUT}`)
console.log(`  ${artists.length} artists${carried ? `, ${carried} with settings carried over` : ''}`)
console.log('\n  Next: restart the app, then run `npm run verify:apis` to see which')
console.log('  Sprout profiles did not match anyone on the list.\n')
